
##add this file in frontend folder

server {
    listen 443 ssl;
    server_name team.armtronix.net;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
